{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "piwigo.mariadb.fullname" . }}-secret
  labels:
    {{- include "piwigo.mariadb.labels" . | nindent 4 }}
type: Opaque
stringData:
  mariadb-user: {{ .Values.mariadb.auth.username | quote }}
  mariadb-password: {{ .Values.mariadb.auth.password | quote }}
  mariadb-database: {{ .Values.mariadb.auth.database | quote }}
{{- end }}
